Update the NUClear codebase to the latest version
Fastcode/NUClearNet.js pull request #21
Opened 2024-01-09 10:12 UTC by TrentHouliston

Updates the NUClear codebase to the latest version to help with some compile errors and improve the stability

2024-01-09 21:08 UTC, Bidski commented on .vscode/settings.json
Looks like you need to add a smudge filter

2024-01-15 06:45 UTC, TrentHouliston commented on .gitignore
> +# .DS_Store
```suggestion
.DS_Store
```

2024-04-29 02:31 UTC, JosephusPaye requested changes

2024-04-29 02:31 UTC, JosephusPaye commented on tests/test.js
Undo the changes in here plz

2024-04-29 02:31 UTC, JosephusPaye commented on .github/workflows/publish-to-npm.yml
> +          node-version: "16.x"
```suggestion
          node-version: "18.x"
```

2024-04-29 02:31 UTC, JosephusPaye commented on .vscode/settings.json
Delete this

2024-04-29 02:35 UTC, TrentHouliston commented on tests/test.js
undone

2024-04-29 02:36 UTC, JosephusPaye approved these changes

2024-04-29 02:39 UTC, merged